# Generated by Django 3.2.12 on 2023-10-11 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_p2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinks',
            old_name='drink',
            new_name='drink_name',
        ),
    ]
